### ISSUE TITLE
How to append to Table?

### ISSUE THREAD

**Issue by HelterSkelterGames** [Ward727a/godot_datatable_plugin#2]
Hello,
I am working on a collection tracker app and was just wondering how I would go about appending data to the DataTable from a line edit. I have tried to append it but I lack the know how, any advice would be helpful. Thanks

**Comment by Ward727a** [comment]
Hey!
Just to be sure, you want to append data to the DataTable from your script while your app is launched?

Because, if you want to do that, you can't, but I could work on a way to do it! :)

**Comment by HelterSkelterGames** [comment]
Thanks for the reply, that is what I intended to do with the project. Thanks

**Comment by Ward727a** [comment]
Alright, I will release an update with some new things, for now I don't know when it will release, I'm still working on it.

If you really need this, I can push the edit on the repo, and inform you when it's done so you just need to download the singleton.gd file on the repo, like you want :)

**Comment by HelterSkelterGames** [comment]
Thank you again, I'm in no big rush for the feature, I can wait. Thanks for your help

**Comment by Ward727a** [comment]
Send the new version that should allow you to do that!
Now you just need to wait for the Godot Asset Store to review it, then download the new update! :)

(check in singleton.gd for: add_item, set_item, remove_item)

Thanks you for your idea!

**Comment by HelterSkelterGames** [comment]
Thank you very much, you are a life saver.
