### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tektrip-biggles** [Ward727a/godot_datatable_plugin#3]
As someone coming from the UE4 world, this looks like a great plugin! But it does feel like GPL isn't really compatible with releasing commercial games unless you also release the game itself's source code as open source, right? Is that your intention or am I perhaps misunderstanding how that works?

**Comment by Ward727a** [comment]
Hello!
I will not gonna lie: I'm totally lost with all those license thing, I just seen lot of thing in GPL-3.0 license on git, so I set it like that.
If that license poses a problem like what you said, I will change for a more appropriate one, maybe MIT License, but I'm totally open for suggestion for this.

To be clear: I don't want to force you to release your game source code, it's your work, and it's you to decide that :)

**Comment by tektrip-biggles** [comment]
Wow! Speedy response :-) 

Yeah, my understanding is that MIT license allows you to use the code in commercial products without issue, but the GPL's "Copy Left" clauses basically mean any product that includes GPL code has to _also_ be released under GPL or equivalent. It's great for some situations, like when you are providing a service instead of a product but probably not the best thing for a game plugin.

**Comment by Ward727a** [comment]
Ok! Well, I will change the license for MIT for the next version, I don't want to add a new version "just" for this, but it will be done!

Thanks you for your advice! =)

**Comment by Ward727a** [comment]
Done in the latest commit, it will be edited on the Godot asset store once the new version is totally ready, need to do some testing here and there (The new version has the collection system implemented, so I want to re-check all the plugin feature before publishing it)

I will close this issue once the Godot Asset Store is edited! :)

Commits:

Update for github:
https://github.com/Ward727a/godot_datatable_plugin/commit/253f330ab20a75e67bc582f942147d7d01be882b
https://github.com/Ward727a/godot_datatable_plugin/commit/b7d8b2e8461d364feef0d53ac36d7545a4ae37e6

Update inside addon folder:
https://github.com/Ward727a/godot_datatable_plugin/commit/a2d243c27d74e79c1f0227191cbba36ae8c93e7b
https://github.com/Ward727a/godot_datatable_plugin/commit/641898dba20cddbc6fef90c21399011722ccbcf8

**Comment by tektrip-biggles** [comment]
Amazing, thank you!!
